name: CI for Commits

on: 
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Mise à jour vers v3

      - name: Set up Python
        uses: actions/setup-python@v3  # Mise à jour vers v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          cd frontend
          pip install -U pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd frontend
          make test
